name:                polimorf
version:             0.7.4
github:              "kawu/polimorf"
license:             BSD3
author:              "Jakub Waszczuk"
maintainer:          "waszczuk.kuba@gmail.com"
copyright:           "2012-2019 IPI PAN, Jakub Waszczuk"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handling the PoliMorf dictionary
category:            Natural Language Processing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kawu/polimorf#readme>

dependencies:
- base >= 4 && < 5
- containers
- text
- binary
# - text-binary >= 0.1 && < 0.2

library:
  source-dirs: src
